version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: '07:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: dependabot
    groups:
      all-dependencies:
        patterns:
          - '*'
  - package-ecosystem: pip
    directories:
      - /**
    schedule:
      interval: weekly
      day: wednesday
      time: '07:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: dependabot
    groups:
      all-dependencies:
        patterns:
          - '*'
